#!/bin/bash
rm -rf dist

# CJS
mkdir -p dist/cjs
echo '{ "type": "commonjs" }' > dist/cjs/package.json
BABEL_ENV=cjs babel src --out-dir dist/cjs "$@"

# ESM
mkdir -p dist/esm
echo '{ "type": "module" }' > dist/esm/package.json
BABEL_ENV=esm babel src --out-dir dist/esm "$@"